# Generated by Django 6.1 on 2026-10-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_marketplaceproduct_marketplaceorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacecommission',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
