# Generated by Django 6.1.1 on 2026-10-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_feeconfiguration_financialoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialoperation',
            name='operation_type',
            field=models.CharField(choices=[('transfer', 'Transfert'), ('deposit', 'Depot'), ('withdraw', 'Retrait'), ('mobile_money', 'Mobile Money'), ('wenze', 'WENZE'), ('commission', 'Commission'), ('gift', 'Cadeau')], max_length=50),
        ),
    ]
