# Generated by Django 6.1 on 2026-10-01 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_bankcountryaccess_bankcurrencyaccess'),
        ('financial_routing', '0001_initial'),
        ('partner_finance', '0003_alter_partnerapplication_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('partner_type', models.CharField(choices=[('BANK', 'Banque'), ('MOBILE_MONEY', 'Mobile Money'), ('VISA', 'Visa'), ('FINANCIAL_PARTNER', 'Partenaire financier'), ('INTERNAL', 'Interne NSIKAY')], max_length=30)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('country_name', models.CharField(blank=True, max_length=120)),
                ('external_reference', models.CharField(blank=True, max_length=150)),
                ('certified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('SUSPENDED', 'Suspendu'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_partners_approved', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_partner_registry', to='banking.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_partners_created', to=settings.AUTH_USER_MODEL)),
                ('partner_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_partner_registry', to='partner_finance.partnerapplication')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['partner_type', 'active'], name='financial_r_partner_d6c07c_idx'), models.Index(fields=['country_code', 'active'], name='financial_r_country_bca917_idx'), models.Index(fields=['status', 'active'], name='financial_r_status_7c8a33_idx')],
            },
        ),
    ]
