# Generated by Django 6.1 on 2026-10-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_routing', '0002_financialpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialfeerule',
            name='fee_type',
            field=models.CharField(choices=[('TRANSFER_INTERNAL', 'Transfert interne NSIKAY'), ('TRANSFER_EXTERNAL', 'Transfert externe'), ('TRANSFER_MOBILE_MONEY', 'Transfert Mobile Money'), ('TRANSFER_VISA', 'Transfert Visa'), ('WITHDRAWAL', 'Retrait'), ('WENZE', 'Vente WENZE')], max_length=40, unique=True),
        ),
    ]
