# Generated by Django 5.2.17 on 2026-10-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nsikay_profiles', '0002_specialized_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('professional', 'Professionnel'), ('company', 'Entreprise'), ('service', 'Service'), ('shop', 'Commerce'), ('creator', 'Créateur'), ('artist', 'Artiste'), ('sport', 'Sport'), ('training', 'Formation'), ('school', 'École'), ('association', 'Association'), ('media', 'Média'), ('agriculture', 'Agriculture'), ('technology', 'Technologie'), ('logistics', 'Logistique'), ('other', 'Autre')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('suspended', 'Suspendue')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Privé')], default='public', max_length=20)),
                ('certification_required', models.BooleanField(default=False)),
                ('certification_status', models.CharField(choices=[('not_required', 'Non requise'), ('pending', 'En attente'), ('certified', 'Certifiée'), ('rejected', 'Refusée'), ('expired', 'Expirée')], default='not_required', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='nsikay_profiles.nsikayprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('active', 'Actif'), ('completed', 'Terminé'), ('suspended', 'Suspendu')], default='planned', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='nsikay_activities.activity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='draft', max_length=20)),
                ('certification_required', models.BooleanField(default=False)),
                ('certification_status', models.CharField(choices=[('not_required', 'Non requise'), ('pending', 'En attente'), ('certified', 'Certifié'), ('rejected', 'Refusé'), ('expired', 'Expiré')], default='not_required', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='nsikay_activities.activity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['profile', 'activity_type'], name='nsikay_acti_profile_f5e658_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', 'status'], name='nsikay_acti_activit_a0f518_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['country', 'city'], name='nsikay_acti_country_d466eb_idx'),
        ),
    ]
