# Generated by Django 5.2.17 on 2026-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsikay_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('professional', 'Professionnel'), ('company', 'Entreprise'), ('service', 'Service'), ('shop', 'Commerce'), ('creator', 'Créateur'), ('artist', 'Artiste'), ('sport', 'Sport'), ('training', 'Formation'), ('school', 'École'), ('association', 'Association'), ('media', 'Média'), ('agriculture', 'Agriculture'), ('technology', 'Technologie'), ('gift_reseller', 'Revendeur de cadeaux'), ('logistics', 'Logistique'), ('other', 'Autre')], default='other', max_length=30),
        ),
    ]
