# Generated by Django 5.2.17 on 2026-10-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsikay_activities', '0002_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('professional', 'Professionnel'), ('company', 'Entreprise'), ('bank', 'Banque'), ('service', 'Service'), ('shop', 'Commerce'), ('creator', 'Créateur'), ('artist', 'Artiste'), ('sport', 'Sport'), ('training', 'Formation'), ('school', 'École'), ('health', 'Santé'), ('association', 'Association'), ('institution', 'Institution'), ('agent', 'Agent / Expert'), ('media', 'Média'), ('agriculture', 'Agriculture'), ('technology', 'Technologie'), ('gift_reseller', 'Revendeur de cadeaux'), ('logistics', 'Logistique'), ('other', 'Autre')], default='other', max_length=30),
        ),
    ]
