# Generated by Django 5.2.17 on 2026-10-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsikay_activities', '0003_alter_activity_activity_type'),
        ('nsikay_profiles', '0003_nsikayprofile_uniq_primary_profile_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='migrated_activity', to='nsikay_profiles.nsikayprofile'),
        ),
    ]
