# Generated by Django 6.1 on 2026-10-01 13:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('PRINCIPAL', 'Compte principal'), ('GIFTS', 'Compte cadeaux'), ('FEES', 'Compte commissions et frais'), ('PAYOUT', 'Compte retraits')], db_index=True, max_length=20)),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifie'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('CLOSED', 'Ferme')], db_index=True, default='PLANNED', max_length=20)),
                ('bank_partner', models.CharField(blank=True, default='', max_length=200)),
                ('external_reference', models.CharField(blank=True, default='', max_length=200)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24)),
                ('description', models.TextField(blank=True, default='')),
                ('is_internal_ledger', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_type', 'currency', 'code'],
                'indexes': [models.Index(fields=['account_type', 'currency'], name='financial_a_account_47eccf_idx'), models.Index(fields=['status', 'currency'], name='financial_a_status_6635f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nsikay_reference', models.CharField(db_index=True, max_length=150)),
                ('bank_reference', models.CharField(blank=True, default='', max_length=150)),
                ('transaction_type', models.CharField(max_length=80)),
                ('currency', models.CharField(max_length=3)),
                ('nsikay_amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('bank_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('MATCHED', 'Rapproche'), ('DIFFERENCE', 'Difference'), ('CANCELLED', 'Annule')], db_index=True, default='PENDING', max_length=20)),
                ('transaction_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='financial_accounts.financialaccount')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['status', 'currency'], name='financial_a_status_dc54c2_idx'), models.Index(fields=['nsikay_reference'], name='financial_a_nsikay__fc9ebc_idx'), models.Index(fields=['bank_reference'], name='financial_a_bank_re_8bc0f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GiftFinancialLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('operation_type', models.CharField(choices=[('PURCHASE', 'Achat de cadeaux'), ('SEND', 'Envoi de cadeaux'), ('RECEIVE', 'Reception de cadeaux'), ('WITHDRAWAL', 'Retrait'), ('REFUND', 'Remboursement'), ('ADJUSTMENT', 'Ajustement')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('buyer_reference', models.CharField(blank=True, default='', max_length=150)),
                ('sender_reference', models.CharField(blank=True, default='', max_length=150)),
                ('beneficiary_reference', models.CharField(blank=True, default='', max_length=150)),
                ('related_reference', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_ledger_entries', to='financial_accounts.financialaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation_type', 'currency'], name='financial_a_operati_9738ae_idx'), models.Index(fields=['buyer_reference'], name='financial_a_buyer_r_37e6f3_idx'), models.Index(fields=['beneficiary_reference'], name='financial_a_benefic_87c3a9_idx')],
            },
        ),
    ]
