# Generated by Django 6.1 on 2026-09-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_walletcommission_walletoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('DEPOSIT', 'Dépôt'), ('WITHDRAW', 'Retrait'), ('TRANSFER', 'Transfert'), ('SECURITY', 'Sécurité')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='wallet.wallet')),
            ],
        ),
    ]
