# Generated by Django 6.1 on 2026-09-29 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_walletkycprofile_walletcurrencybalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Certifié'), ('BLOCKED', 'Bloqué')], default='PENDING', max_length=20)),
                ('certified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='wallet.wallet')),
            ],
        ),
    ]
