# Generated by Django 5.2.17 on 2026-10-03 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'E-mail')], default='email', max_length=20)),
                ('destination', models.CharField(blank=True, max_length=320)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('used', models.BooleanField(default=False)),
                ('requested_ip_hash', models.CharField(blank=True, max_length=128)),
                ('user_agent_hash', models.CharField(blank=True, max_length=128)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_recovery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='pwdrec_user_requested_idx'), models.Index(fields=['expires_at', 'used'], name='pwdrec_expiry_used_idx')],
            },
        ),
    ]
