# Generated by Django 5.2.17 on 2026-10-02 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('destination_type', models.CharField(choices=[('INTERNAL', 'Destination NSIKAY'), ('EXTERNAL', 'Réseau externe')], default='INTERNAL', max_length=20)),
                ('channel_type', models.CharField(choices=[('NSIKAY_TV', 'NSIKAY TV'), ('ECONOMIE', 'Économie'), ('SPORT', 'Sport & Loisirs'), ('CULTURE', 'Culture & Arts'), ('TECHNOLOGIE', 'Technologie & Innovation'), ('AGRICULTURE', 'Agriculture & Agronomie'), ('ENVIRONNEMENT', 'Environnement'), ('SOCIAL', 'Social'), ('RELIGION', 'Religion & Histoire'), ('ADULT', '+18'), ('EVENEMENTS', 'Événements'), ('PUBLICITE', 'Publicité'), ('YOUTUBE', 'YouTube'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('TWITCH', 'Twitch'), ('LINKEDIN', 'LinkedIn'), ('RTMP', 'RTMP personnalisé'), ('SRT', 'SRT personnalisé'), ('HLS', 'HLS personnalisé')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('endpoint_url', models.URLField(blank=True, default='')),
                ('account_label', models.CharField(blank=True, default='', max_length=255)),
                ('secret_reference', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['destination_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('asset_type', models.CharField(choices=[('VIDEO', 'Vidéo'), ('FILM', 'Film'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('PROGRAM', 'Programme TV'), ('MUSIC', 'Musique'), ('JINGLE', 'Jingle'), ('ADVERTISING', 'Publicité'), ('REPORTAGE', 'Reportage'), ('INTERVIEW', 'Interview'), ('ARCHIVE', 'Archive'), ('DOCUMENT', 'Document')], default='VIDEO', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='media_library/assets/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_library/thumbnails/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(blank=True, default='', max_length=150)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('READY', 'Prêt'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_library_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_seconds', models.PositiveIntegerField(default=0)),
                ('end_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='media_library.mediaasset')),
                ('destinations', models.ManyToManyField(blank=True, related_name='segments', to='media_library.mediadestination')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('READY', 'Prêt'), ('LIVE', 'En direct'), ('PUBLISHED', 'Publié'), ('STOPPED', 'Arrêté'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='media_library.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_distributions_created', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='media_library.mediadestination')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'destination'), name='unique_media_asset_destination')],
            },
        ),
    ]
