# Generated by Django 5.2.17 on 2026-10-02 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NsikayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('person', 'Personne'), ('professional', 'Professionnel / Métier'), ('company', 'Entreprise'), ('bank', 'Banque'), ('school', 'École / Université'), ('training', 'Centre de formation'), ('health', 'Hôpital / Santé'), ('association', 'Association / ONG'), ('institution', 'Institution'), ('artist', 'Artiste / Créateur'), ('agent', 'Agent / Expert')], max_length=30)),
                ('display_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=250)),
                ('professional_title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=150)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Privé')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='draft', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('certification_required', models.BooleanField(default=False)),
                ('certification_status', models.CharField(default='not_required', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nsikay_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'profile_type'], name='nsikay_prof_user_id_2cc8d5_idx'), models.Index(fields=['profile_type', 'status'], name='nsikay_prof_profile_71657b_idx'), models.Index(fields=['country', 'profile_type'], name='nsikay_prof_country_d7696b_idx')],
            },
        ),
    ]
