# Generated by Django 5.2.17 on 2026-10-03 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsikay_profiles', '0002_specialized_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nsikayprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='uniq_primary_profile_per_user'),
        ),
    ]
