# Generated by Django 5.2.17 on 2026-10-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsikay_profiles', '0003_nsikayprofile_uniq_primary_profile_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsikayprofile',
            name='identity_document_photo',
            field=models.ImageField(blank=True, null=True, upload_to='nsikay/identity/document/'),
        ),
        migrations.AddField(
            model_name='nsikayprofile',
            name='identity_with_document_photo',
            field=models.ImageField(blank=True, null=True, upload_to='nsikay/identity/verification/'),
        ),
        migrations.AddField(
            model_name='nsikayprofile',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='nsikay/identity/personal/'),
        ),
    ]
