# Generated by Django 6.1 on 2026-09-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('active_global', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CountryServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('country_code', 'country_name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('validated_by_admin', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_control.countryservicestatus')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_control.globalservice')),
            ],
        ),
        migrations.AddField(
            model_name='globalservice',
            name='countries',
            field=models.ManyToManyField(blank=True, through='service_control.ServiceActivation', to='service_control.countryservicestatus'),
        ),
    ]
