# Generated by Django 6.1 on 2026-09-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_required', models.BooleanField(default=True)),
                ('partner_bank_required', models.BooleanField(default=False)),
                ('health_insurance_required', models.BooleanField(default=False)),
                ('remote_activation_allowed', models.BooleanField(default=True)),
                ('admin_validation_required', models.BooleanField(default=True)),
                ('country_authorization_required', models.BooleanField(default=True)),
                ('financial_partner_required', models.BooleanField(default=False)),
                ('active_by_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='service_control.globalservice')),
            ],
        ),
    ]
