# Generated by Django 6.1 on 2026-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_control', '0002_servicerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryservicestatus',
            name='is_operational',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='countryservicestatus',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='countryservicestatus',
            name='iso2_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='countryservicestatus',
            name='iso_numeric_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AddIndex(
            model_name='countryservicestatus',
            index=models.Index(fields=['country_code', 'is_primary'], name='service_con_country_1f5a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='countryservicestatus',
            index=models.Index(fields=['country_code', 'is_operational'], name='service_con_country_e89970_idx'),
        ),
    ]
