# Generated by Django 6.1.1 on 2026-10-01 14:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_nsikay', '0010_alter_virtualgift_options_gifttransaction_amount_eur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftResellerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Cree'), ('DISTRIBUTED', 'Distribue'), ('AGREEMENT_ACCEPTED', 'Accord accepte'), ('AGREEMENT_LOCKED', 'Accord verrouille'), ('SOLD', 'Vendu'), ('ALLOCATED', 'Repartition'), ('TRANSFERRED', 'Transfere'), ('EXCHANGED', 'Echange'), ('BLOCKED', 'Bloque')], db_index=True, max_length=30)),
                ('reference', models.CharField(db_index=True, max_length=150)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_reseller_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_network_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('CLOSED', 'Ferme')], db_index=True, default='PENDING', max_length=20)),
                ('reseller_code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nsikay_gift_reseller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reseller_code'],
            },
        ),
        migrations.CreateModel(
            name='GiftInventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('official_value_eur', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency_reference', models.CharField(default='EUR', max_length=3)),
                ('source', models.CharField(choices=[('NSIKAY', 'NSIKAY'), ('RESELLER', 'Revendeur'), ('CREDIT', 'Credit'), ('EXCHANGE', 'Echange')], default='NSIKAY', max_length=20)),
                ('credit_only', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('DISTRIBUTED', 'Distribue'), ('SOLD', 'Vendu'), ('EXCHANGED', 'Echange'), ('REDEEMED', 'Utilise'), ('BLOCKED', 'Bloque')], db_index=True, default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_units', to='api_nsikay.virtualgift')),
                ('current_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_units', to='gift_resellers.networkmember')),
                ('current_reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_units', to='gift_resellers.reseller')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('official_value_eur', models.DecimalField(decimal_places=2, max_digits=20)),
                ('member_percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('principal_reseller_percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('nsikay_percentage', models.DecimalField(decimal_places=3, default=Decimal('5.000'), max_digits=6)),
                ('other_percentage', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_ACCEPTANCE', "En attente d'acceptation"), ('ACCEPTED', 'Accepte'), ('LOCKED', 'Verrouille'), ('CANCELLED', 'Annule')], db_index=True, default='DRAFT', max_length=25)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_agreements', to='api_nsikay.virtualgift')),
                ('previous_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='gift_resellers.distributionagreement')),
                ('network_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_agreements', to='gift_resellers.networkmember')),
                ('principal_reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_agreements', to='gift_resellers.reseller')),
            ],
        ),
        migrations.CreateModel(
            name='ResellerNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='gift_resellers.reseller')),
            ],
        ),
        migrations.AddField(
            model_name='networkmember',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='gift_resellers.resellernetwork'),
        ),
        migrations.CreateModel(
            name='ResellerSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('official_value_eur', models.DecimalField(decimal_places=2, max_digits=20)),
                ('retail_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('retail_currency', models.CharField(default='EUR', max_length=3)),
                ('nsikay_base_eur', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nsikay_amount_eur', models.DecimalField(decimal_places=2, max_digits=20)),
                ('member_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('principal_reseller_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payee'), ('SETTLED', 'Reglee'), ('CANCELLED', 'Annulee'), ('REFUNDED', 'Remboursee')], db_index=True, default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='gift_resellers.distributionagreement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_purchases', to=settings.AUTH_USER_MODEL)),
                ('gift_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='gift_resellers.giftinventoryunit')),
                ('network_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='gift_resellers.networkmember')),
                ('principal_reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='gift_resellers.reseller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_type', models.CharField(choices=[('MEMBER', 'Part membre'), ('PRINCIPAL_RESELLER', 'Part revendeur principal'), ('NSIKAY', 'Part NSIKAY'), ('OTHER', 'Autre part')], max_length=30)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=8)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('reference', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='gift_resellers.resellersale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='networkmember',
            constraint=models.UniqueConstraint(fields=('network', 'user'), name='uniq_gift_network_member'),
        ),
    ]
