# Generated by Django 6.1.1 on 2026-10-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_resellers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='saleallocation',
            constraint=models.UniqueConstraint(fields=('sale', 'allocation_type'), name='uniq_sale_allocation_type'),
        ),
    ]
