# Generated by Django 5.2.17 on 2026-10-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_resellers', '0002_saleallocation_uniq_sale_allocation_type'),
        ('nsikay_activities', '0002_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_reseller', to='nsikay_activities.activity'),
        ),
    ]
