# Generated by Django 6.1.1 on 2026-10-01 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_marketplacecommission_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=50, unique=True)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('transfer', 'Transfert'), ('deposit', 'Dépôt'), ('withdraw', 'Retrait'), ('mobile_money', 'Mobile Money'), ('wenze', 'WENZE'), ('commission', 'Commission'), ('gift', 'Cadeau')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
