# Generated by Django 6.1.1 on 2026-10-01 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_financialoperation_operation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('account_reference', models.CharField(max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankRoutingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('commission', 'Commission'), ('card', 'Carte'), ('wenze', 'WENZE'), ('advertising', 'Publicité'), ('event', 'Événement')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.partnerbankaccount')),
            ],
        ),
    ]
