# Generated by Django 6.1.1 on 2026-10-01 23:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_partnerbankaccount_bankroutingoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialControlReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('country', models.CharField(default='GLOBAL', max_length=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(default='generated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(default='GLOBAL', max_length=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('destination', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NSIKAYRevenueFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('wenze', 'WENZE'), ('gift', 'Cadeaux'), ('ticket', 'Billetterie'), ('advertising', 'Publicité'), ('transfer', 'Transfert'), ('commission', 'Commission')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('country', models.CharField(default='GLOBAL', max_length=10)),
                ('routed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('TRANSACTION', 'Transaction'), ('BLOCK', 'Blocage'), ('ADMIN', 'Action administrateur'), ('KYC', 'ContrÃ´le KYC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouvert'), ('MATCHED', 'RapprochÃ©'), ('REVIEW', 'ContrÃ´le')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankroutingoperation',
            name='operation_type',
            field=models.CharField(choices=[('commission', 'Commission'), ('card', 'Carte'), ('wenze', 'WENZE'), ('advertising', 'PublicitÃ©'), ('event', 'Ã‰vÃ©nement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financialledger',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'DÃ©pÃ´t'), ('WITHDRAW', 'Retrait'), ('TRANSFER', 'Transfert'), ('FEE', 'Frais'), ('EXCHANGE', 'Change')], max_length=30),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'PayÃ©e'), ('DELIVERED', 'LivrÃ©e'), ('CANCELLED', 'AnnulÃ©e')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='merchantpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'PayÃ©'), ('FAILED', 'Ã‰chec')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='walletsecuritystatus',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('BLOCKED', 'BloquÃ©'), ('REVIEW', 'ContrÃ´le')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'DÃ©pÃ´t'), ('withdraw', 'Retrait'), ('transfer', 'Transfert'), ('purchase', 'Achat'), ('reward', 'RÃ©compense')], max_length=50),
        ),
    ]
