# Generated by Django 6.1.1 on 2026-10-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_financialauditlog_financialcontrolreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('total_operations', models.IntegerField(default=0)),
                ('suspicious_operations', models.IntegerField(default=0)),
                ('status', models.CharField(default='generated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialComplianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('result', models.CharField(default='approved', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudDetectionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.IntegerField()),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='medium', max_length=50)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletSecurityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('risk_level', models.CharField(default='low', max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
