# Generated by Django 5.2.17 on 2026-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_compliancereport_financialcompliancelog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialoperation',
            name='operation_type',
            field=models.CharField(choices=[('transfer', 'Transfert'), ('deposit', 'DÃ©pÃ´t'), ('withdraw', 'Retrait'), ('mobile_money', 'Mobile Money'), ('wenze', 'WENZE'), ('commission', 'Commission'), ('gift', 'Cadeau')], max_length=50),
        ),
    ]
