# Generated by Django 5.2.17 on 2026-10-03 16:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('certification', '0004_nsikaycertification_activity_ref_and_more'),
        ('finance', '0014_alter_financialoperation_operation_type'),
        ('wenze', '0005_alter_wenzeorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('GOODS', 'Transport de marchandises'), ('PASSENGER', 'Transport de personnes'), ('BOTH', 'Marchandises et personnes')], default='BOTH', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('certification_required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('validated_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_companies', to='certification.nsikaycertification')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_profile', to='business.company')),
            ],
            options={
                'ordering': ['company__name'],
            },
        ),
        migrations.CreateModel(
            name='TransportDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_category', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transport_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='transport.transportcompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('GOODS_DELIVERY', 'Livraison de marchandises'), ('RIDE', 'Course / trajet'), ('DAILY_RENTAL', 'Location à la journée'), ('INTERCITY', 'Transport interurbain'), ('OTHER', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('pricing_mode', models.CharField(choices=[('FIXED', 'Prix fixe'), ('DISTANCE', 'Selon distance'), ('TIME', 'Selon durée'), ('QUOTE', 'Sur devis')], default='FIXED', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_services', to='finance.currency')),
                ('transport_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='transport.transportcompany')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Voiture'), ('TAXI', 'Taxi'), ('MOTORCYCLE', 'Moto'), ('VAN', 'Minibus / Van'), ('BUS', 'Bus'), ('TRUCK', 'Camion'), ('PICKUP', 'Pick-up'), ('TRAILER', 'Remorque'), ('OTHER', 'Autre')], max_length=20)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('cargo_capacity_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BUSY', 'En service'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactif')], default='AVAILABLE', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transport_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='transport.transportcompany')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('destination_address', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('REQUESTED', 'Demandée'), ('ACCEPTED', 'Acceptée'), ('DRIVER_ASSIGNED', 'Conducteur assigné'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='REQUESTED', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_rides', to='finance.currency')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_rides', to=settings.AUTH_USER_MODEL)),
                ('transport_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_rides', to='transport.transportcompany')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_rides', to='transport.transportdriver')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='transport.transportservice')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_rides', to='transport.transportvehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('pickup_address', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('REQUESTED', 'Demandée'), ('CONFIRMED', 'Confirmée'), ('ACTIVE', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='REQUESTED', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_rentals', to='finance.currency')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_rentals', to=settings.AUTH_USER_MODEL)),
                ('transport_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_rentals', to='transport.transportcompany')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='transport.transportservice')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_rentals', to='transport.transportvehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WenzeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField(blank=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Transporteur assigné'), ('PICKED_UP', 'Colis récupéré'), ('IN_TRANSIT', 'En transit'), ('DELIVERED', 'Livré'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('tracking_reference', models.CharField(max_length=100, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wenze_deliveries', to='transport.transportdriver')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_delivery', to='wenze.wenzeorder')),
                ('transport_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wenze_deliveries', to='transport.transportcompany')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wenze_deliveries', to='transport.transportvehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TransportTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='transport.passengerrental')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='transport.passengerride')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='transport.wenzedelivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
