# Generated by Django 6.1 on 2026-09-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_partnerapproval'),
        ('finance', '0002_currency_remove_payment_transaction_and_more'),
        ('partner_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deposit_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=30)),
                ('verified_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bank')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_finance.partnerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('withdrawal', 'Retrait'), ('deposit', 'Dépôt'), ('purchase', 'Achat'), ('transfer', 'Transfert')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_finance.partnerapplication')),
            ],
        ),
    ]
