# Generated by Django 6.1.1 on 2026-09-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('finance', '0002_currency_remove_payment_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankservice',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_type',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.wallet'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.CreateModel(
            name='BankingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdraw', 'Retrait'), ('transfer', 'Transfert'), ('payment', 'Paiement')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
            ],
        ),
        migrations.DeleteModel(
            name='BankCountry',
        ),
        migrations.DeleteModel(
            name='BankService',
        ),
        migrations.DeleteModel(
            name='CreditRequest',
        ),
        migrations.DeleteModel(
            name='InsuranceOffer',
        ),
    ]
