# Generated by Django 6.1.1 on 2026-09-29 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_bankbalance_banktransaction'),
        ('finance', '0002_currency_remove_payment_transaction_and_more'),
        ('partner_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bank')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_finance.partnerapplication')),
            ],
        ),
    ]
