# Generated by Django 6.1 on 2026-09-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_control', '0002_servicerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDashboardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activate', 'Activation'), ('disable', 'Désactivation'), ('validation', 'Validation'), ('rejection', 'Refus')], max_length=50)),
                ('admin_user', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_control.countryservicestatus')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_control.globalservice')),
            ],
        ),
    ]
