# Generated by Django 6.1 on 2026-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalCountryConfigurationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=150)),
                ('selected_count', models.PositiveIntegerField()),
                ('selected_codes', models.TextField()),
                ('action', models.CharField(default='configuration_240_pays', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='service_das_created_9f30f8_idx'), models.Index(fields=['admin_user'], name='service_das_admin_u_a9574b_idx')],
            },
        ),
    ]
