# Generated by Django 6.1 on 2026-09-30 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_control', '0003_countryservicestatus_is_operational_and_more'),
        ('service_dashboard', '0003_configuration_rollback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceActivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validee'), ('rejected', 'Refusee'), ('activated', 'Activee'), ('cancelled', 'Annulee')], db_index=True, default='pending', max_length=20)),
                ('certification_checked', models.BooleanField(default=False)),
                ('health_insurance_checked', models.BooleanField(default=False)),
                ('bank_partner_checked', models.BooleanField(default=False)),
                ('financial_partner_checked', models.BooleanField(default=False)),
                ('country_authorization_checked', models.BooleanField(default=False)),
                ('admin_validated', models.BooleanField(default=False)),
                ('validation_message', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_requests', to='service_control.countryservicestatus')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_activation_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_requests', to='service_control.globalservice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', 'country', 'status'], name='service_das_service_f36723_idx'), models.Index(fields=['requested_by', 'status'], name='service_das_request_d03843_idx'), models.Index(fields=['country', 'status'], name='service_das_country_3272c8_idx')],
            },
        ),
    ]
