# Generated by Django 6.1 on 2026-09-30 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_dashboard', '0004_serviceactivationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceactivationrequest',
            name='beneficiary_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsikay_activation_beneficiary_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
