# Generated by Django 6.1 on 2026-09-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('bank', 'Banque'), ('partner', 'Partenaire financier'), ('currency', 'Devise'), ('country', 'Pays'), ('service', 'Service')], max_length=50)),
                ('applicant_name', models.CharField(max_length=200)),
                ('documents_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.validationrequest')),
            ],
        ),
    ]
