# Generated by Django 6.1 on 2026-09-29 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('banking', '0010_bankcountryaccess_bankcurrencyaccess'),
        ('finance', '0002_currency_remove_payment_transaction_and_more'),
        ('partner_finance', '0002_partnerdeposit_supplytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('banks_count', models.IntegerField(default=0)),
                ('partners_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='validationrequest',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='validationrequest',
            name='documents_verified',
        ),
        migrations.RemoveField(
            model_name='validationrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='validationrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='validationrequest',
            name='applicant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='validationrequest',
            name='request_type',
            field=models.CharField(choices=[('bank', 'Certification Banque'), ('currency', 'Validation Devise'), ('partner', 'Validation Partenaire Financier'), ('country', 'Supervision Pays')], max_length=50),
        ),
        migrations.CreateModel(
            name='BankCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_certification_relation', to='banking.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_approval_relation', to='banking.bank')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_approval_relation', to='finance.currency')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_approval_relation', to='partner_finance.partnerapplication')),
            ],
        ),
        migrations.DeleteModel(
            name='OfficialContract',
        ),
    ]
