# Generated by Django 6.1 on 2026-09-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_countrysupervision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCountryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('access_level', models.CharField(default='STANDARD', max_length=100)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankCurrencyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=50)),
                ('access_level', models.CharField(default='STANDARD', max_length=100)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankServiceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryBankAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
