# Generated by Django 6.1 on 2026-09-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_bankpartner_bankpartnercurrency_bankpartnerservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBankAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.bankpartner')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.countrysupervision')),
            ],
        ),
        migrations.CreateModel(
            name='CountryCurrencyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.countrysupervision')),
            ],
        ),
        migrations.CreateModel(
            name='CountryRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('regulation_status', models.CharField(default='active', max_length=50)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.countrysupervision')),
            ],
        ),
    ]
