# Generated by Django 6.1 on 2026-09-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_countrybankaccess_countrycurrencyaccess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySupervisionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=100)),
                ('code_iso', models.CharField(max_length=10, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('devises_autorisees', models.JSONField(default=list)),
                ('niveau_conformite', models.CharField(default='en_verification', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banques_autorisees', models.ManyToManyField(blank=True, to='administration.bankpartner')),
            ],
        ),
    ]
