# Generated by Django 6.1 on 2026-09-30 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_nsikayadminrole_nsikaypermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validee'), ('expired', 'Expiree'), ('rejected', 'Refusee')], default='pending', max_length=20)),
                ('validated_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insured_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insurances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['insured_user', 'status'], name='administrat_insured_bf8703_idx'), models.Index(fields=['country', 'status'], name='administrat_country_71cfc5_idx'), models.Index(fields=['policy_number'], name='administrat_policy__367d01_idx')],
            },
        ),
    ]
