# Generated by Django 5.2.17 on 2026-10-05 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidature', 'verbose_name_plural': 'Candidatures'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created_at'], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='application',
            name='administration_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employment_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='administration_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='administrative_status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_VERIFICATION', 'En vérification'), ('VALIDEE', 'Validée'), ('SUSPENDUE', 'Suspendue'), ('REFUSEE', 'Refusée')], default='BROUILLON', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='certification_status',
            field=models.CharField(choices=[('NON_CERTIFIEE', 'Non certifiée'), ('EN_ATTENTE', 'Certification en attente'), ('CERTIFIEE', 'Certifiée'), ('SUSPENDUE', 'Certification suspendue')], default='NON_CERTIFIEE', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_employment_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='administration_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_VERIFICATION', 'En vérification'), ('VALIDEE', 'Validée'), ('PUBLIEE', 'Publiée'), ('SUSPENDUE', 'Suspendue'), ('REFUSEE', 'Refusée'), ('EXPIREE', 'Expirée')], default='BROUILLON', max_length=30),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_job_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('PUBLIEE', 'Publiée'), ('SUSPENDUE', 'Suspendue')], default='BROUILLON', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_employment_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('PUBLIEE', 'Publiée'), ('SUSPENDUE', 'Suspendue')], default='BROUILLON', max_length=30),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_employment_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
