# Generated by Django 5.2.17 on 2026-10-05 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_application_options_alter_company_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_VERIFICATION', 'En vérification'), ('CERTIFIE', 'Certifié'), ('SUSPENDU', 'Suspendu'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('certification_date', models.DateTimeField(blank=True, null=True)),
                ('administration_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_insurance_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partenaire assurance',
                'verbose_name_plural': 'Partenaires assurance',
                'ordering': ['name'],
                'permissions': [('review_insurancepartner', 'Examiner un assureur partenaire'), ('certify_insurancepartner', 'Certifier un assureur partenaire'), ('suspend_insurancepartner', 'Suspendre un assureur partenaire')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('coverage', models.TextField(help_text='Description de la couverture proposée.')),
                ('duration_months', models.PositiveIntegerField(default=12)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré')], default='BROUILLON', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('administration_note', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='jobs.insurancepartner')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_insurance_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit assurance',
                'verbose_name_plural': 'Produits assurance',
                'ordering': ['partner__name', 'name'],
                'permissions': [('validate_insuranceproduct', "Valider un produit d'assurance"), ('suspend_insuranceproduct', "Suspendre un produit d'assurance")],
            },
        ),
        migrations.CreateModel(
            name='EmploymentInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SELECTIONNEE', 'Sélectionnée'), ('SOUSCRIPTION_EN_COURS', 'Souscription en cours'), ('SOUSCRITE', 'Souscrite'), ('EN_VERIFICATION', 'En vérification'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('EXPIREE', 'Expirée'), ('SUSPENDUE', 'Suspendue')], default='SELECTIONNEE', max_length=30)),
                ('policy_number', models.CharField(blank=True, max_length=150)),
                ('certificate_reference', models.CharField(blank=True, max_length=150)),
                ('coverage_start', models.DateField(blank=True, null=True)),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='jobs/insurance/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('administration_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_insurances', to='jobs.company')),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment_insurances', to='jobs.joboffer')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_employment_insurances', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_insurances', to='jobs.insuranceproduct')),
            ],
            options={
                'verbose_name': 'Assurance emploi',
                'verbose_name_plural': 'Assurances emploi',
                'ordering': ['-created_at'],
                'permissions': [('verify_employmentinsurance', 'Vérifier une assurance emploi'), ('approve_employmentinsurance', 'Valider une assurance emploi')],
            },
        ),
    ]
