# Generated by Django 5.2.17 on 2026-10-05 02:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_insurancepartner_insuranceproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('contract_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('EN_ATTENTE_TRAVAILLEUR', 'En attente du travailleur'), ('ACCEPTE_TRAVAILLEUR', 'Accepté par le travailleur'), ('REFUSE_TRAVAILLEUR', 'Refusé par le travailleur'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('salary_currency', models.CharField(default='EUR', max_length=10)),
                ('document', models.FileField(blank=True, upload_to='jobs/contracts/')),
                ('administration_note', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('worker_acceptance_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('worker_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('worker_acceptance_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_employment_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrat de travail',
                'verbose_name_plural': 'Contrats de travail',
                'ordering': ['-created_at'],
                'permissions': [('review_employmentcontract', 'Examiner un contrat de travail'), ('validate_employmentcontract', 'Valider un contrat de travail'), ('accept_employmentcontract', "Enregistrer l'acceptation du travailleur")],
            },
        ),
        migrations.CreateModel(
            name='EmploymentContractAnnex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(upload_to='jobs/contracts/annexes/')),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='SOUMISE', max_length=30)),
                ('administration_note', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexes', to='jobs.employmentcontract')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_employment_contract_annexes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annexe du contrat',
                'verbose_name_plural': 'Annexes des contrats',
                'ordering': ['created_at'],
                'permissions': [('review_employmentcontractannex', 'Examiner une annexe de contrat'), ('validate_employmentcontractannex', 'Valider une annexe de contrat')],
            },
        ),
        migrations.CreateModel(
            name='EmploymentEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PREPARE', 'Préparé'), ('EN_ATTENTE_CONTRAT', 'En attente du contrat'), ('ENGAGE', 'Engagement confirmé'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PREPARE', max_length=40)),
                ('position_title', models.CharField(max_length=255)),
                ('engagement_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('work_location', models.CharField(blank=True, max_length=255)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('salary_currency', models.CharField(default='EUR', max_length=10)),
                ('administration_note', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employment_engagement', to='jobs.application')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_employment_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement',
                'verbose_name_plural': 'Engagements',
                'ordering': ['-created_at'],
                'permissions': [('review_employmentengagement', 'Examiner un engagement professionnel'), ('validate_employmentengagement', 'Valider un engagement professionnel'), ('cancel_employmentengagement', 'Annuler un engagement professionnel')],
            },
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='engagement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employment_contract', to='jobs.employmentengagement'),
        ),
    ]
