# Generated by Django 6.1 on 2026-09-29 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('volume', models.IntegerField(default=100)),
                ('noise_reduction', models.BooleanField(default=True)),
                ('equalizer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CameraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('resolution', models.CharField(default='4K', max_length=50)),
                ('fps', models.IntegerField(default=60)),
                ('hdr', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='regie/logo/')),
                ('position', models.CharField(default='bottom', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TextAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('animation_type', models.CharField(max_length=100)),
                ('duration', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transition_type', models.CharField(max_length=100)),
                ('duration', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('effect_type', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('intensity', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='LiveProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv_regie.broadcastscene')),
            ],
        ),
        migrations.AddField(
            model_name='broadcastscene',
            name='overlay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv_regie.overlay'),
        ),
        migrations.AddField(
            model_name='broadcastscene',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv_regie.transition'),
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('camera', 'Camera'), ('live', 'Live'), ('stream', 'Streaming'), ('archive', 'Archive'), ('mobile', 'Mobile')], max_length=50)),
                ('url', models.URLField(blank=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv_regie.cameradevice')),
            ],
        ),
        migrations.AddField(
            model_name='broadcastscene',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_regie.videosource'),
        ),
    ]
