# Generated by Django 6.1 on 2026-09-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_regie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CameraSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source_type', models.CharField(choices=[('IP', 'Camera IP'), ('RTMP', 'Source RTMP'), ('HDMI', 'HDMI Capture'), ('SDI', 'SDI Broadcast'), ('WEBRTC', 'WebRTC Live')], default='IP', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('resolution', models.CharField(default='4K', max_length=50)),
                ('frame_rate', models.IntegerField(default=60)),
                ('is_live', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stream_url', models.URLField()),
                ('quality', models.CharField(default='4K Ultra HD', max_length=50)),
                ('recording_enabled', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_regie.camerasystem')),
            ],
        ),
        migrations.CreateModel(
            name='RegieScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='broadcastscene',
            name='overlay',
        ),
        migrations.RemoveField(
            model_name='broadcastscene',
            name='source',
        ),
        migrations.RemoveField(
            model_name='broadcastscene',
            name='transition',
        ),
        migrations.RemoveField(
            model_name='liveproduction',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='liveproduction',
            name='operator',
        ),
        migrations.DeleteModel(
            name='VideoFilter',
        ),
        migrations.RenameField(
            model_name='videoeffect',
            old_name='enabled',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='audiocontrol',
            name='equalizer',
        ),
        migrations.RemoveField(
            model_name='audiocontrol',
            name='noise_reduction',
        ),
        migrations.RemoveField(
            model_name='textanimation',
            name='name',
        ),
        migrations.AddField(
            model_name='audiocontrol',
            name='audio_effect',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='audiocontrol',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textanimation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textanimation',
            name='position',
            field=models.CharField(default='bottom', max_length=50),
        ),
        migrations.AddField(
            model_name='textanimation',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textanimation',
            name='title',
            field=models.CharField(default='Animation', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoeffect',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='audiocontrol',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='textanimation',
            name='animation_type',
            field=models.CharField(default='fade', max_length=100),
        ),
        migrations.AlterField(
            model_name='textanimation',
            name='duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='videoeffect',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='regiescene',
            name='audio',
            field=models.ManyToManyField(blank=True, to='tv_regie.audiocontrol'),
        ),
        migrations.AddField(
            model_name='regiescene',
            name='cameras',
            field=models.ManyToManyField(blank=True, to='tv_regie.camerasystem'),
        ),
        migrations.AddField(
            model_name='regiescene',
            name='effects',
            field=models.ManyToManyField(blank=True, to='tv_regie.videoeffect'),
        ),
        migrations.AddField(
            model_name='regiescene',
            name='texts',
            field=models.ManyToManyField(blank=True, to='tv_regie.textanimation'),
        ),
        migrations.AddField(
            model_name='broadcastschedule',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv_regie.regiescene'),
        ),
        migrations.DeleteModel(
            name='Overlay',
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
        migrations.DeleteModel(
            name='BroadcastScene',
        ),
        migrations.DeleteModel(
            name='CameraDevice',
        ),
        migrations.DeleteModel(
            name='VideoSource',
        ),
        migrations.DeleteModel(
            name='LiveProduction',
        ),
    ]
