# Generated by Django 6.1 on 2026-09-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_nsikay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlementaccount',
            name='bank',
        ),
        migrations.DeleteModel(
            name='BankDeposit',
        ),
        migrations.DeleteModel(
            name='PartnerBank',
        ),
        migrations.DeleteModel(
            name='SettlementAccount',
        ),
    ]
