# Generated by Django 6.1 on 2026-09-29 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_nsikay', '0006_countryconfiguration_apigatewaylog_cloudfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvchannel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tvchannel',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tvchannel',
            old_name='stream_url',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='advertisementplacement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisementplacement',
            name='name',
            field=models.CharField(default='NSIKAY', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisementplacement',
            name='stream_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvchannel',
            name='category',
            field=models.CharField(choices=[('economie', 'Économie'), ('sport', 'Sport & Loisirs'), ('culture', 'Culture & Arts'), ('technologie', 'Technologie & Innovation'), ('agriculture', 'Agriculture & Agronomie'), ('social', 'Social'), ('religion', 'Religion & Histoire'), ('adult', '+18')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvchannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvchannel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tvchannel',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvchannel',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
