# Generated by Django 6.1.1 on 2026-10-01 14:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_nsikay', '0009_virtualgift_catalog_fields'),
        ('tv_regie', '0002_broadcastschedule_camerasystem_livestream_regiescene_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualgift',
            options={'ordering': ['display_order', 'value_eur', 'id']},
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='amount_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='financial_ledger_reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='live',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_transactions', to='tv_regie.livestream'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='payment_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_transactions', to='api_nsikay.socialpost'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='virtualgift',
            name='value_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=20),
        ),
        migrations.AddIndex(
            model_name='virtualgift',
            index=models.Index(fields=['active', 'display_order'], name='api_nsikay__active_077b24_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualgift',
            index=models.Index(fields=['currency_reference', 'value_eur'], name='api_nsikay__currenc_264cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualgift',
            index=models.Index(fields=['category', 'active'], name='api_nsikay__categor_8385d9_idx'),
        ),
    ]
