# Generated by Django 6.1 on 2026-09-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificationdocument',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='certificationrequest',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='request',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='institutionprofile',
            name='owner',
        ),
        migrations.CreateModel(
            name='FieldInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('identity_checked', models.BooleanField(default=False)),
                ('documents_checked', models.BooleanField(default=False)),
                ('report', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'Agent affecté'), ('visit', 'Visite réalisée'), ('submitted', 'Rapport envoyé'), ('approved', 'Validé'), ('rejected', 'Refusé')], default='assigned', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.certificationagent')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.validationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certification.fieldinspection')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CertificationDocument',
        ),
        migrations.DeleteModel(
            name='CertificationRequest',
        ),
        migrations.DeleteModel(
            name='FieldAgent',
        ),
        migrations.DeleteModel(
            name='InspectionReport',
        ),
        migrations.DeleteModel(
            name='IdentityVerification',
        ),
        migrations.DeleteModel(
            name='InstitutionProfile',
        ),
    ]
