# Generated by Django 5.2.17 on 2026-10-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_nsikaycertification_certificationhistory'),
        ('nsikay_activities', '0004_activity_source_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsikaycertification',
            name='activity_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nsikay_certification', to='nsikay_activities.activity'),
        ),
        migrations.AlterField(
            model_name='nsikaycertification',
            name='certification_type',
            field=models.CharField(choices=[('activity', 'Activité'), ('person', 'Personne'), ('company', 'Entreprise'), ('agent', 'Agent'), ('bank', 'Banque'), ('partner', 'Partenaire')], max_length=50),
        ),
    ]
