# Generated by Django 6.1 on 2026-10-01 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('TRANSFER_INTERNAL', 'Transfert interne NSIKAY'), ('TRANSFER_EXTERNAL', 'Transfert externe'), ('WITHDRAWAL', 'Retrait'), ('WENZE', 'Vente WENZE')], max_length=40, unique=True)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, default='', help_text='Code ISO du pays. Vide = règle internationale.', max_length=10)),
                ('country_name', models.CharField(blank=True, default='', max_length=120)),
                ('currency_code', models.CharField(blank=True, default='', help_text='EUR, USD, CDF ou autre devise approuvée.', max_length=10)),
                ('source_type', models.CharField(choices=[('WENZE', 'WENZE'), ('EVENT', 'Événement'), ('TICKET', 'Billetterie'), ('ADVERTISING', 'Publicité'), ('MEMBERSHIP', 'Adhésion'), ('GIFT', 'Cadeau'), ('COMMISSION', 'Commission'), ('CREDIT', 'Crédit'), ('INVESTMENT', 'Investissement'), ('OTHER', 'Autre')], max_length=30)),
                ('source_name', models.CharField(blank=True, default='', help_text='Nom précis de la source de revenu.', max_length=255)),
                ('operation_type', models.CharField(choices=[('REVENUE', 'Revenu'), ('TRANSFER', 'Transfert'), ('WITHDRAWAL', 'Retrait'), ('DEPOSIT', 'Dépôt'), ('SETTLEMENT', 'Règlement')], default='REVENUE', max_length=30)),
                ('partner_type', models.CharField(choices=[('BANK', 'Banque'), ('MOBILE_MONEY', 'Mobile Money'), ('VISA', 'Visa'), ('FINANCIAL_PARTNER', 'Partenaire financier'), ('INTERNAL', 'NSIKAY interne')], default='BANK', max_length=30)),
                ('partner_name', models.CharField(help_text='Banque ou partenaire financier destinataire.', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_country', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_reference', models.CharField(blank=True, default='', help_text='Référence interne du compte. Ne pas stocker de données bancaires sensibles non nécessaires.', max_length=255)),
                ('destination_label', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Plus le nombre est petit, plus la règle est prioritaire.')),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente de validation'), ('APPROVED', 'Approuvé'), ('SUSPENDED', 'Suspendu'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=30)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_routing_rules_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_routing_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRoutingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Créée'), ('UPDATED', 'Modifiée'), ('APPROVED', 'Approuvée'), ('SUSPENDED', 'Suspendue'), ('ACTIVATED', 'Activée'), ('DEACTIVATED', 'Désactivée')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='financial_routing.financialroutingrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialroutingrule',
            index=models.Index(fields=['country_code', 'currency_code'], name='financial_r_country_aae162_idx'),
        ),
        migrations.AddIndex(
            model_name='financialroutingrule',
            index=models.Index(fields=['source_type', 'active'], name='financial_r_source__24e2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='financialroutingrule',
            index=models.Index(fields=['status', 'active'], name='financial_r_status_6e7548_idx'),
        ),
        migrations.AddIndex(
            model_name='financialroutingrule',
            index=models.Index(fields=['partner_type', 'partner_name'], name='financial_r_partner_e598fb_idx'),
        ),
    ]
