# Generated by Django 6.1.1 on 2026-09-29 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0006_bankbalance_banktransaction'),
        ('finance', '0002_currency_remove_payment_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('social_links', models.TextField(blank=True)),
                ('documents', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('certification', 'Certification'), ('approved', 'Certifié'), ('rejected', 'Refusé')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_verified', models.BooleanField(default=False)),
                ('documents_verified', models.BooleanField(default=False)),
                ('certified_by', models.CharField(blank=True, max_length=200)),
                ('certification_date', models.DateTimeField(auto_now_add=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner_finance.partnerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.bank')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_finance.partnerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_finance.partnerapplication')),
            ],
        ),
    ]
