# Generated by Django 6.1 on 2026-09-29 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_bankcountryaccess_bankcurrencyaccess'),
        ('finance', '0002_currency_remove_payment_transaction_and_more'),
        ('partner_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bank')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_finance.partnerwallet')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_added', models.DecimalField(decimal_places=2, max_digits=20)),
                ('approved_by_bank', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner_finance.partnerdeposit')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_finance.partnerwallet')),
            ],
        ),
    ]
