# Generated by Django 6.1 on 2026-09-29 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_bankcountryaccess_bankcurrencyaccess'),
        ('partner_finance', '0002_partnerdeposit_supplytransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_finance_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnercertification',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_certification_relation', to='partner_finance.partnerapplication'),
        ),
        migrations.AlterField(
            model_name='partnerdeposit',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_partner_deposit_relation', to='banking.bank'),
        ),
        migrations.AlterField(
            model_name='partnerdeposit',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_deposit_relation', to='partner_finance.partnerwallet'),
        ),
        migrations.AlterField(
            model_name='partnersupply',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_supply_relation', to='partner_finance.partnerapplication'),
        ),
        migrations.AlterField(
            model_name='partnerwallet',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_wallet_relation', to='partner_finance.partnerapplication'),
        ),
        migrations.AlterField(
            model_name='supplytransaction',
            name='deposit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_supply_transaction_relation', to='partner_finance.partnerdeposit'),
        ),
        migrations.AlterField(
            model_name='supplytransaction',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_transaction_relation', to='partner_finance.partnerwallet'),
        ),
    ]
