# Generated by Django 6.1.1 on 2026-09-29 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('private', 'Profil privé'), ('professional', 'Profil professionnel'), ('company', 'Entreprise'), ('artist', 'Artiste'), ('member', 'Membre association')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('social_links', models.JSONField(default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
