# Generated by Django 6.1 on 2026-10-01 11:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wenzeorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wenzeorder',
            name='payment_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='wenzeorder',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Portefeuille NSIKAY'), ('MOBILE_MONEY', 'Mobile Money'), ('VISA', 'Carte Visa')], default='WALLET', max_length=20),
        ),
        migrations.AddField(
            model_name='wenzeorder',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
