# Generated by Django 6.1.1 on 2026-10-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_marketplacecommission_rate'),
        ('wenze', '0003_migrate_currency_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wenzeorder',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wenze_orders', to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='wenzeorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payée'), ('PROCESSING', 'En traitement'), ('SHIPPED', 'Expédiée'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='wenzeproduct',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wenze_products', to='finance.currency'),
        ),
    ]
