# Generated by Django 6.1.1 on 2026-10-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenze', '0004_alter_wenzeorder_currency_alter_wenzeorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wenzeorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'PayÃ©e'), ('PROCESSING', 'En traitement'), ('SHIPPED', 'ExpÃ©diÃ©e'), ('COMPLETED', 'TerminÃ©e'), ('CANCELLED', 'AnnulÃ©e')], default='PENDING', max_length=20),
        ),
    ]
